### ISSUE TITLE
Documentation URL is not valid

### ISSUE THREAD

**Issue by lanzone1** [luratic/SealMetrics#1]
Hi, the documentation link in `metadata.yaml` points to https://www.luratic.com/posts/templates/tags/sealmetrics/, which does not exist. 
Please update this link to post to a valid page.

Otherwise, the template looks good. Thanks!

**Comment by luratic-devs** [comment]
Hi @lanzone1!

Thank you very much for the warning, the page is already created, but we still have to elaborate the documentation.

Thanks!

**Comment by lanzone1** [comment]
Any update here? The documentation page is still blank.
